### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by krissss**
conventional-changelog-cli is dev only

### CODE REVIEW

**Comment by krissss** [comment]
image
image

**Comment by krissss** [comment]
Can publish a tag or release?

**Comment by xiaweiss** [comment]
ok, wait a minute

**Comment by krissss** [comment]
Thank you

**Comment by krissss** [comment]
No npm version release? 
https://www.npmjs.com/package/vite-plugin-ali-oss?activeTab=versions

**Comment by xiaweiss** [comment]
CI failed, I tried a few times. It is now released v1.0.9

**Comment by xiaweiss** [comment]
Thank you for feedback 😊

**Pull request merged**
